#!/bin/zsh

if [[ -n "$__EXECUTED_GIT_COMMAND" || -n "$__EXECUTED_HG_COMMAND" ]];
then
  update_current_vcs_vars
  [[ -n "$__EXECUTED_GIT_COMMAND" ]] && unset __EXECUTED_GIT_COMMAND
	[[ -n "$__EXECUTED_HG_COMMAND" ]] && unset __EXECUTED_HG_COMMAND
fi
