#!/bin/zsh
# http://sebastiancelis.com/2009/11/16/zsh-prompt-git-users/
# https://bitbucket.org/Josh/mercurial-for-zsh/

unset __CURRENT_GIT_BRANCH
unset __CURRENT_GIT_BRANCH_STATUS
unset __CURRENT_GIT_BRANCH_IS_DIRTY
#unset __CURRENT_HG_BRANCH
#unset __CURRENT_HG_BRANCH_STATUS
#unset __CURRENT_HG_BRANCH_IS_DIRTY

local gtst="$(git status 2>/dev/null)"
#local hgst="$(hg status 2>/dev/null)"
#local hgbr="$(hg branch 2>/dev/null)"

if [[ -n "$gtst" ]]; then
  local -a arr
  arr=(${(f)gtst})

  if [[ $arr[1] =~ 'Not currently on any branch.' ]]; then
    __CURRENT_GIT_BRANCH='no-branch'
  else
    __CURRENT_GIT_BRANCH="${arr[1][(w)4]}";
  fi

  if [[ $arr[2] =~ 'Your branch is' ]]; then
    if [[ $arr[2] =~ 'ahead' ]]; then
      __CURRENT_GIT_BRANCH_STATUS='ahead'
    elif [[ $arr[2] =~ 'diverged' ]]; then
      __CURRENT_GIT_BRANCH_STATUS='diverged'
    else
      __CURRENT_GIT_BRANCH_STATUS='behind'
    fi
  fi

  if [[ ! $gtst =~ 'nothing to commit' ]]; then
      __CURRENT_GIT_BRANCH_IS_DIRTY='1'
  fi
fi

if [ -n "$hgbr" ]; then
  local -a arr
  arr=(${(f)hgbr})
  export __CURRENT_HG_BRANCH="$(echo $arr[1])"
fi

if [ -n "$hgst" ]; then
  if echo $hgst | grep "nothing to commit (working directory clean)" >/dev/null; then
    export __CURRENT_HG_BRANCH_IS_DIRTY='1'
  fi
fi
