#!/bin/bash
function vasa {
  if [ ! "$*" ]; then
    echo 'Nothing to tweet!'
    return 1
  fi
  # gd $*
  echo "$* #vasa" | bti
}

# Google tts
tts() {
  curl -sA 'Mozilla' "http://translate.google.com/translate_tts?tl=en&q=$(echo $* | sed 's#[ ,]#\+#g')" | play -t mp3 - > /dev/null 2>&1;
}
