#!/bin/bash

# SSH-AGENT {{{1
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
  echo "Initializing new SSH agent..."
  /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  echo succeeded
  chmod 600 "${SSH_ENV}"
  . "${SSH_ENV}" > /dev/null
  /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
  . "${SSH_ENV}" > /dev/null
  #ps ${SSH_AGENT_PID} doesn't work under cywgin
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent;
  }
else
  start_agent;
fi
# }}}

function vasa {
  if [ ! "$*" ]; then
    echo 'Nothing to tweet!'
    return 1
  fi
  # gd $*
  echo "$* #vasa" | bti
}

# Google tts
tts() {
  curl -sA 'Mozilla' "http://translate.google.com/translate_tts?tl=en&q=$(echo $* | sed 's#[ ,]#\+#g')" | play -t mp3 - > /dev/null 2>&1;
}

color-blocks () {
  echo
  local width=$(( ($COLUMNS / 16) -1 ))
  local chars
  local pre=$(( ( $COLUMNS - ($width+1)*16)/2 ))
  for ((i=0; i<$width; i++)); do chars+="░" ; done
  for ((i=0; i<$pre; i++)); do echo -n " " ; done
  for ((i=0; i<=7; i++)); do echo -en "\e[3${i}m${chars} \e[1;3${i}m${chars}\e[m "; done; echo; echo
  unset i
}
